### ISSUE TITLE
Fix token support

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/registration#15]
Since token is no longer a module but exists in core, we should remove all checks to see if the token module exists before adding token support.

Additionally, it looks like the token replacements aren't working in the notification email -- probably because the if `module_exists()` check would have prevented them from being used or even tested before now. 

So far, I have been unable to determine why registration tokens don't get replaced when both node and user tokens in the email are replaced without an issue. 

No replacement patterns are being provided for the registration entity in Backdrop, but they were added just fine in Drupal 7. I'm not sure why yet, but will note my theories here:

* Entities need to provide a `token type` in order for tokens to be replaced -- it appears as though registration entities do though...
* Entities need to be a PHP class in Backdrop, maybe there's something missing in the Registration entity that ie necessary for tokens...

**Comment by jenlampton** [comment]
I found it! It turns out the entity class nedded to define a `bundle()` method that returned the Regisration type. Added this in an *presto* token replacements!

**Comment by hosef** [comment]
I have merged the changes in Jen's PR.
