### ISSUE TITLE
Incompatibility with Entity Plus 1.x-1.0.10

### ISSUE THREAD

**Issue by mazzech** [backdrop-contrib/registration#23]
Seems that Entity Plus 1.x-1.0.10 combined with Registration Views lead to a white screen... going to /update.php throws this here

Fatal error: Uncaught Error: Class 'RegistrationViewsController' not found in /home/MYSITE/modules/entity_plus/views/entity_plus.views.inc:30 Stack trace: #0 /home/lugoture/www/backdrop.mazzemedia.ch/core/includes/module.inc(960): entity_plus_views_data() #1 /home/lugoture/www/backdrop.mazzemedia.ch/core/modules/views/includes/cache.inc(90): module_invoke_all('views_data') #2 /home/lugoture/www/backdrop.mazzemedia.ch/core/modules/views/includes/cache.inc(75): _views_fetch_data_build() #3 /home/lugoture/www/backdrop.mazzemedia.ch/core/modules/views/views.module(1141): _views_fetch_data(NULL, true, false) #4 /home/MYSITE/modules/entity_plus/views/entity_plus.views.inc(320): views_fetch_data() #5 /home/lugoture/www/backdrop.mazzemedia.ch/core/modules/views/includes/utility.inc(456): entity_plus_views_plugins() #6 /home/lugoture/www/backdrop.mazzemedia.ch/core/modules/views/includes/cache.inc(148): views_discover_plugins() #7 /home/lugoture/www/back in /home/MYSITE/modules/entity_plus/views/entity_plus.views.inc on line 30

**Comment by hosef** [comment]
I have pushed a new commit to the 1.x-1.x branch. If you get the latest dev code from Github, it should fix this issue.
