### ISSUE TITLE
Add maintainers to README.

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/registration#24]
Just noticing that there is no official maintainer listed? 

I see that @hosef has merged code in the past, but @docwilmot also seems to be involved.

We are planning on using this module for https://events.backdropcms.org and there are a number of outstanding PR's. 

Are we looking for a maintainer for this module?

**Comment by docwilmot** [comment]
I dont think we ever did formally decide between @hosef and me who would maintain but he did most of the finishing touches and released it. And I somehow am not subscribed to notifications so never saw all these PRs.

But even if we don't formally agree to maintain it, I'd prefer to let @hosef chime in before making any decisions. Maybe @hosef can merge in @jenlampton's many PRs.

**Comment by stpaultim** [comment]
A couple of updates.

1) We still don't have anyone listed as the maintainer
2) There are a number of commits since the last release - some of these might be important
3) We are using the Registration module on https://events.backdropcms.org/ (but none of the sub-modules)
4) The current release (as well as dev version) have a pretty serious bug that breaks sites when the Registration Views sub-module is enabled. https://github.com/backdrop-contrib/registration/issues/28

@jenlampton, @hosef and @docwilmot

**Comment by jenlampton** [comment]
Here's a PR that adds both @hosef and @docwilmot as maintainers. If either of you don't want to be on there, feel free to remove yourselves. And if both of you wish not to maintain, I would like to volunteer.
