### ISSUE TITLE
Permissions Not Working?

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/registration#25]
I'm experimenting with a registration form for events.backdropcms.org and initially we experimented with allowing anonymous users to register. We then decided that users should have to create an account to register, so I removed those permissions, but anonymous users are still able to register. 

I'm not finding any way to prevent anonymous registration?

Am I configuring things incorrectly or are permissions not working as expected?

The only two permissions that anonymous users have on this site are:

* View published content
* Use the Filtered HTML text format

**Comment by stpaultim** [comment]
I will try to work around this problem by putting the registration form in a block or layout that is only accessible to authenticated users. 

Using Layout visibility rules did not work. 
https://github.com/backdrop/backdrop-issues/issues/4972

**Comment by docwilmot** [comment]
Meanwhile, pushed a fix to a new branch `access-fix`, maybe you could test that. Permissions on the module were actually totally useless since Backdrop has very different `entity_access()` function from D7. Will need to keep that in mind for other ports.

**Comment by stpaultim** [comment]
@docwilmot - I added your changes to an already heavily patched version of the module and got the following results:

1) The registration form itself was no longer visible when permissions were removed. I tested anonymous registration and the form was ONLY visible if permissions were set. 
2) However, when I tried to register anonymously, I got the following error:

`Error: Class name must be a valid object or a string in entity_get_controller() (line 534 of /app/www/core/modules/entity/entity.module).`

I will test your a clean version of your branch as well. 

NOTE: Prior to your changes, I was able to register anonymously without an error - even when I didn't have permission to do so.

**Comment by stpaultim** [comment]
@docwilmot - I spun up a clean site and tested with the 1.x-1.x version of this module. I was able to register for an event as expected (I did not test permissions). 

When I replaced with the 1.x-1.x version with your branch to fix access problems and tried to register, I got the same error as above:

`Error: Class name must be a valid object or a string in entity_get_controller() (line 534 of /app/core/modules/entity/entity.module).`

**Comment by stpaultim** [comment]
EDIT: This was incorrect. I though that the module was working, but it because I had accidentally merged the changes submitted by @docwilmot that hide the form based upon permissions, but causes other errors. So it appeared that access permissions were working, but they are not. 

~~For the record. Permissions for this module do seem to be working on events.backdropcms.org, but it is a heavily patched version of the module. I am not sure why they weren't working for me locally yesterday. Maybe, I didn't have the same version of the module locally at the time.~~

~~We may want to hold off on any additional fixes, until we get all the current PR's merged - to avoid fixing things that might already have a fix.~~

**Comment by docwilmot** [comment]
I modified the wrong method. Should be better now.

**Comment by stpaultim** [comment]
Thanks @docwilmot, what would we do without you?

I'm done for today, but will try to test this soon. For the events.backdropcms.org site, I've temporarily substituted "content access" module to achieve my goals.

**Comment by docwilmot** [comment]
> Thanks @docwilmot, what would we do without you?

You'd ping @hosef, more than likely. 😄

**Comment by jenlampton** [comment]
I've created a PR from @docwilmot's branch: https://github.com/backdrop-contrib/registration/pull/29

I'm getting a fatal error when using the changes from the access-fix branch:
```
Fatal error: Cannot redeclare Registration::bundle() in backdrop/modules/contrib/registration/lib/registration.entity.inc on line 252
```
So I'm going to remove that addition and push an update.

**Comment by hosef** [comment]
I have merged the changes from Jen's PR, so I am closing this issue. If more changes need to be made, please let me know.
