### ISSUE TITLE
Call to undefined function entity_view()

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/registration#27]
I noticed in the events.b.org site that there were 2 views titled "Registrations (Registrations)":
- one links to `/admin/registrations` and works fine 👍 
- the other links to `/registrations` and throws a "Call to undefined function entity_view()" error 👎 

Not sure if this due to a bug in the module, or misconfiguration on the specific site (and I don't have the time/energy to investigate at the moment). Thought I'd mentioned it here anyway.

**Comment by hosef** [comment]
I just checked on the event site, and both of those views appear to be working, so whatever was causing the issue must have been fixed.
