### ISSUE TITLE
Notice: _field_info_prepare_instance_display()

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/registration#38]
This is happening when you first install the module and add a Registration field to a node. It happens in multiple places - one of them is in the Field UI when adding the field, and when you clear caches on that page. 

The problem is that the registration field info includes a formatter called `registration_default`, but this formatter is never defined. The solution, I believe, is to either define this formatter in `registration_field_formatter_info()`, or to choose a different default formatter in `registration_field_info()`, for example, `registration_link`, which seems to be a good default option.

BTW, a similar error exists in D7 - but there the function _field_info_prepare_instance_display is actually a method in class FieldInfo.

PHP 7.4
Backdrop 1.24.0

[EDIT] The error goes away if you go to Manage Display and select and save a formatter there.

**Comment by hosef** [comment]
I changed the default display formatter to registration_link as you suggested.
